apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: geth-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: geth.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: geth-service
            port:
              number: 8545
